[project]
name = "openaiconversationenhanced"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "Igor Borges", email = "igor@borges.dev" }
]
dependencies = [
    "homeassistant>=2023.10.5",
    "openai>=0.28.1",
]
readme = "README.md"
requires-python = ">= 3.11"

[tool.rye]
managed = true
dev-dependencies = []

#[build-system]
#requires = ["hatchling"]
#build-backend = "hatchling.build"

[tool.poetry]
name = "openaiconversationenhanced"
version = "0.1.0"
description = ""
authors = ["Igor Borges <igor@borges.dev>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.11.6"
homeassistant = "2023.10.5"
openai = "^0.28.1"
kani = {extras = ["openai"], version = "^0.5.1"}
requests = "^2.31.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
