[project]
name = "jarvis"
version = "0.1.0"
description = ""
authors = ["Igor Borges <igor@borges.dev>"]
readme = "README.md"

requires-python = ">=3.13"

dependencies = [
    "homeassistant>=2024.6.4",
    "httpx>=0.27.0",
]
