[tool.poetry]
name = "jarvis"
version = "0.1.0"
description = ""
authors = ["Igor Borges <igor@borges.dev>"]
license = "Apache License 2.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "3.11.6"
homeassistant = "2023.10.5"
openai = "^0.28.1"
kani = {extras = ["openai"], version = "^0.5.1"}
aiohttp = "3.8.5"
google-api-python-client = "^2.105.0"
langchain = "^0.0.351"
yfinance = "0.2.31"
langchain-experimental = "^0.0.47"
google-auth-oauthlib = "^1.2.0"
tmdbv3api = "^1.9.0"
wikipedia = "^1.4.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
