[tool.poetry]
name = "jarvis"
version = "0.1.0"
description = ""
authors = ["Igor Borges <igor@borges.dev>"]
license = "Apache License 2.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "3.11"
homeassistant = "2023.10.5"
openai = "^0.27.8"
kani = {extras = ["huggingface", "llama", "openai"], version = "^0.5.1"}
aiohttp = "3.8.5"
google-api-python-client = "^2.105.0"
langchain = "^0.0.325"
numexpr = "^2.8.7"
#instructor = "^0.2.9"
#actionweaver = "^0.0.10"
openai-functions = "^1.0.2"
simpleaichat = "^0.2.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
