[tool.poetry]
name = "jarvis"
version = "0.1.0"
description = ""
authors = ["Igor Borges <igor@borges.dev>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "~3.12"

fastapi = "^0.110.0"
uvicorn = "^0.27.1"
langserve = "^0.0.44"
sse-starlette = "^2.0.0"

pydantic = "^1"
langchain = "^0.1.9"
langchain-community = "^0.0.24"
langchain-openai = "^0.0.8"
langchain-experimental = "^0.0.52"

wikipedia = "^1.4.0"
google-api-python-client = "^2.119.0"
google-auth-httplib2 = "^0.2.0"
google-auth-oauthlib = "^1.2.0"
beautifulsoup4 = "^4.12.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
