[tool.poetry]
name = "jarvis"
version = "0.1.0"
description = ""
authors = ["Igor Borges <igor@borges.dev>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.12.1"

fastapi = "^0.110.2"
uvicorn = "^0.29.0"
langserve = "^0.1.0"
sse-starlette = "^2.1.0"

pydantic = "^1"
langchain = "^0.1.16"
langchain-core = "^0.1.45"
langchain-community = "^0.0.34"
langchain-openai = "^0.1.3"
langchain-experimental = "^0.0.57"
langgraph = "^0.0.38"

wikipedia = "^1.4.0"
langchain-google-community = "^1.0.2"
google-api-python-client = "^2.126.0"
google-auth-httplib2 = "^0.2.0"
google-auth-oauthlib = "^1.2.0"
beautifulsoup4 = "^4.12.3"
httpx = "^0.27.0"
apscheduler = "^3.10.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
